import importlib.util, os, unittest

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SPEC = importlib.util.spec_from_file_location(
    'build_tours', os.path.join(ROOT, 'cms', 'build-tours.py'))
bt = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(bt)

CH = 'e2350ad8-80af-4c18-a21a-acae6d72283f'


class TestRedirectHtml(unittest.TestCase):
    def test_redirects_to_the_widget_url(self):
        html = bt.go_redirect_html({'id': 's', 'full': True,
                                    'widgets': {'en': f'{CH}/experience-calendar/1'}})
        self.assertIn(f'https://widgets.bokun.io/online-sales/{CH}/experience-calendar/1', html)
        self.assertIn('http-equiv="refresh"', html)
        self.assertIn('location.replace', html)

    def test_is_noindex(self):
        html = bt.go_redirect_html({'id': 's', 'full': True, 'widgets': {'en': f'{CH}/x/1'}})
        self.assertIn('noindex', html)

    def test_no_page_without_a_widget(self):
        self.assertIsNone(bt.go_redirect_html({'id': 's', 'full': True, 'widgets': {}}))

    def test_no_page_for_an_unpriced_tour(self):
        self.assertIsNone(bt.go_redirect_html(
            {'id': 's', 'full': False, 'widgets': {'en': f'{CH}/x/1'}}))


class TestInstagramRedirectPreserved(unittest.TestCase):
    def test_go_kamakura_survives_untouched(self):
        # Live link from the Zenrise Instagram profile. Out of scope: must not
        # be deleted or regenerated by this build.
        p = os.path.join(ROOT, 'go', 'kamakura', 'index.html')
        self.assertTrue(os.path.exists(p), 'go/kamakura was removed; it is out of scope')
        with open(p) as f:
            self.assertIn('1272734', f.read())

    def test_generated_slugs_cannot_collide_with_it(self):
        import json
        with open(os.path.join(ROOT, 'cms', 'tours-config.json')) as f:
            cfg = json.load(f)
        self.assertNotIn('kamakura', {e['slug'] for e in cfg['tours'].values()})


if __name__ == '__main__':
    unittest.main()
